{"level":"ERROR","location":"[__symbol_conversion:1375] data_ws","message":"object of type 'module' has no len()","timestamp":"2024-05-29 09:26:37,274+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/Users/krfinance18/Desktop/Python/test/lib/python3.12/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1313, in __symbol_conversion\n    total_symbols = len(symbolslst)\n                    ^^^^^^^^^^^^^^^\nTypeError: object of type 'module' has no len()","exception_name":"TypeError"}
{"level":"ERROR","location":"[__symbol_conversion:1375] data_ws","message":"object of type 'module' has no len()","timestamp":"2024-05-29 09:29:23,237+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/Users/krfinance18/Desktop/Python/test/lib/python3.12/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1313, in __symbol_conversion\n    total_symbols = len(symbolslst)\n                    ^^^^^^^^^^^^^^^\nTypeError: object of type 'module' has no len()","exception_name":"TypeError"}
{"level":"ERROR","location":"[__symbol_conversion:1375] data_ws","message":"object of type 'module' has no len()","timestamp":"2024-05-29 09:35:17,421+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/Users/krfinance18/Desktop/Python/test/lib/python3.12/site-packages/websocket/_app.py\", line 428, in setSock\n    dispatcher.read(self.sock.sock, read, check)\n  File \"/Users/krfinance18/Desktop/Python/test/lib/python3.12/site-packages/websocket/_app.py\", line 99, in read\n    if not read_callback():\n           ^^^^^^^^^^^^^^^\n  File \"/Users/krfinance18/Desktop/Python/test/lib/python3.12/site-packages/websocket/_app.py\", line 442, in read\n    raise e\n  File \"/Users/krfinance18/Desktop/Python/test/lib/python3.12/site-packages/websocket/_app.py\", line 437, in read\n    op_code, frame = self.sock.recv_data_frame(True)\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/krfinance18/Desktop/Python/test/lib/python3.12/site-packages/websocket/_core.py\", line 406, in recv_data_frame\n    frame = self.recv_frame()\n            ^^^^^^^^^^^^^^^^^\n  File \"/Users/krfinance18/Desktop/Python/test/lib/python3.12/site-packages/websocket/_core.py\", line 445, in recv_frame\n    return self.frame_buffer.recv_frame()\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/krfinance18/Desktop/Python/test/lib/python3.12/site-packages/websocket/_abnf.py\", line 338, in recv_frame\n    self.recv_header()\n  File \"/Users/krfinance18/Desktop/Python/test/lib/python3.12/site-packages/websocket/_abnf.py\", line 294, in recv_header\n    header = self.recv_strict(2)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/krfinance18/Desktop/Python/test/lib/python3.12/site-packages/websocket/_abnf.py\", line 373, in recv_strict\n    bytes_ = self.recv(min(16384, shortage))\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/krfinance18/Desktop/Python/test/lib/python3.12/site-packages/websocket/_core.py\", line 529, in _recv\n    return recv(self.sock, bufsize)\n           ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/krfinance18/Desktop/Python/test/lib/python3.12/site-packages/websocket/_socket.py\", line 122, in recv\n    raise WebSocketConnectionClosedException(\nwebsocket._exceptions.WebSocketConnectionClosedException: Connection to remote host was lost.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/Users/krfinance18/Desktop/Python/test/lib/python3.12/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1313, in __symbol_conversion\n    total_symbols = len(symbolslst)\n                    ^^^^^^^^^^^^^^^\nTypeError: object of type 'module' has no len()","exception_name":"TypeError"}
{"level":"ERROR","location":"[__symbol_conversion:1375] data_ws","message":"object of type 'module' has no len()","timestamp":"2024-05-29 09:52:32,008+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/Users/krfinance18/Desktop/Python/test/lib/python3.12/site-packages/websocket/_app.py\", line 428, in setSock\n    dispatcher.read(self.sock.sock, read, check)\n  File \"/Users/krfinance18/Desktop/Python/test/lib/python3.12/site-packages/websocket/_app.py\", line 99, in read\n    if not read_callback():\n           ^^^^^^^^^^^^^^^\n  File \"/Users/krfinance18/Desktop/Python/test/lib/python3.12/site-packages/websocket/_app.py\", line 442, in read\n    raise e\n  File \"/Users/krfinance18/Desktop/Python/test/lib/python3.12/site-packages/websocket/_app.py\", line 437, in read\n    op_code, frame = self.sock.recv_data_frame(True)\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/krfinance18/Desktop/Python/test/lib/python3.12/site-packages/websocket/_core.py\", line 406, in recv_data_frame\n    frame = self.recv_frame()\n            ^^^^^^^^^^^^^^^^^\n  File \"/Users/krfinance18/Desktop/Python/test/lib/python3.12/site-packages/websocket/_core.py\", line 445, in recv_frame\n    return self.frame_buffer.recv_frame()\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/krfinance18/Desktop/Python/test/lib/python3.12/site-packages/websocket/_abnf.py\", line 338, in recv_frame\n    self.recv_header()\n  File \"/Users/krfinance18/Desktop/Python/test/lib/python3.12/site-packages/websocket/_abnf.py\", line 294, in recv_header\n    header = self.recv_strict(2)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/krfinance18/Desktop/Python/test/lib/python3.12/site-packages/websocket/_abnf.py\", line 373, in recv_strict\n    bytes_ = self.recv(min(16384, shortage))\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/krfinance18/Desktop/Python/test/lib/python3.12/site-packages/websocket/_core.py\", line 529, in _recv\n    return recv(self.sock, bufsize)\n           ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/krfinance18/Desktop/Python/test/lib/python3.12/site-packages/websocket/_socket.py\", line 122, in recv\n    raise WebSocketConnectionClosedException(\nwebsocket._exceptions.WebSocketConnectionClosedException: Connection to remote host was lost.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/Users/krfinance18/Desktop/Python/test/lib/python3.12/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1313, in __symbol_conversion\n    total_symbols = len(symbolslst)\n                    ^^^^^^^^^^^^^^^\nTypeError: object of type 'module' has no len()","exception_name":"TypeError"}
{"level":"ERROR","location":"[On_message:1443] data_ws","message":"'symbol'","timestamp":"2024-05-31 10:21:55,043+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/Users/krfinance18/Desktop/Python/test/lib/python3.12/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1434, in On_message\n    self.OnMessage(message)\n  File \"/Users/krfinance18/Desktop/Python/liveadata.py\", line 15, in onmessage\n    symbbol = message['symbol']\n              ~~~~~~~^^^^^^^^^^\nKeyError: 'symbol'","exception_name":"KeyError"}
{"level":"ERROR","location":"[On_message:1443] data_ws","message":"'symbol'","timestamp":"2024-05-31 10:21:55,562+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/Users/krfinance18/Desktop/Python/test/lib/python3.12/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1434, in On_message\n    self.OnMessage(message)\n  File \"/Users/krfinance18/Desktop/Python/liveadata.py\", line 15, in onmessage\n    symbbol = message['symbol']\n              ~~~~~~~^^^^^^^^^^\nKeyError: 'symbol'","exception_name":"KeyError"}
{"level":"ERROR","location":"[On_message:1443] data_ws","message":"'symbol'","timestamp":"2024-05-31 10:21:57,525+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/Users/krfinance18/Desktop/Python/test/lib/python3.12/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1434, in On_message\n    self.OnMessage(message)\n  File \"/Users/krfinance18/Desktop/Python/liveadata.py\", line 15, in onmessage\n    symbbol = message['symbol']\n              ~~~~~~~^^^^^^^^^^\nKeyError: 'symbol'","exception_name":"KeyError"}
{"level":"ERROR","location":"[On_message:1443] data_ws","message":"'symbol'","timestamp":"2024-05-31 10:23:21,270+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/Users/krfinance18/Desktop/Python/test/lib/python3.12/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1434, in On_message\n    self.OnMessage(message)\n  File \"/Users/krfinance18/Desktop/Python/liveadata.py\", line 15, in onmessage\n    symbbol1 = message['symbol']\n               ~~~~~~~^^^^^^^^^^\nKeyError: 'symbol'","exception_name":"KeyError"}
{"level":"ERROR","location":"[On_message:1443] data_ws","message":"'symbol'","timestamp":"2024-05-31 10:23:21,786+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/Users/krfinance18/Desktop/Python/test/lib/python3.12/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1434, in On_message\n    self.OnMessage(message)\n  File \"/Users/krfinance18/Desktop/Python/liveadata.py\", line 15, in onmessage\n    symbbol1 = message['symbol']\n               ~~~~~~~^^^^^^^^^^\nKeyError: 'symbol'","exception_name":"KeyError"}
{"level":"ERROR","location":"[On_message:1443] data_ws","message":"'symbol'","timestamp":"2024-05-31 10:23:25,254+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/Users/krfinance18/Desktop/Python/test/lib/python3.12/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1434, in On_message\n    self.OnMessage(message)\n  File \"/Users/krfinance18/Desktop/Python/liveadata.py\", line 15, in onmessage\n    symbbol1 = message['symbol']\n               ~~~~~~~^^^^^^^^^^\nKeyError: 'symbol'","exception_name":"KeyError"}
{"level":"ERROR","location":"[On_message:1443] data_ws","message":"'symbol'","timestamp":"2024-05-31 21:18:05,279+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/Users/krfinance18/Desktop/Python/test/lib/python3.12/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1434, in On_message\n    self.OnMessage(message)\n  File \"/Users/krfinance18/Desktop/Python/liveadata.py\", line 15, in onmessage\n    symbbol1 = message['symbol']\n               ~~~~~~~^^^^^^^^^^\nKeyError: 'symbol'","exception_name":"KeyError"}
{"level":"ERROR","location":"[On_message:1443] data_ws","message":"'symbol'","timestamp":"2024-05-31 21:18:06,791+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/Users/krfinance18/Desktop/Python/test/lib/python3.12/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1434, in On_message\n    self.OnMessage(message)\n  File \"/Users/krfinance18/Desktop/Python/liveadata.py\", line 15, in onmessage\n    symbbol1 = message['symbol']\n               ~~~~~~~^^^^^^^^^^\nKeyError: 'symbol'","exception_name":"KeyError"}
{"level":"ERROR","location":"[On_message:1443] data_ws","message":"'symbol'","timestamp":"2024-05-31 21:18:10,587+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/Users/krfinance18/Desktop/Python/test/lib/python3.12/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1434, in On_message\n    self.OnMessage(message)\n  File \"/Users/krfinance18/Desktop/Python/liveadata.py\", line 15, in onmessage\n    symbbol1 = message['symbol']\n               ~~~~~~~^^^^^^^^^^\nKeyError: 'symbol'","exception_name":"KeyError"}
{"level":"ERROR","location":"[on_open:1519] data_ws","message":"module 'WatchSocket' has no attribute 'len'","timestamp":"2024-05-31 21:33:10,794+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/Users/krfinance18/Desktop/Python/test/lib/python3.12/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1517, in on_open\n    self.OnOpen()\n  File \"/Users/krfinance18/Desktop/Python/liveadata.py\", line 53, in onopen\n    Numbers =[x for x in range(watchSocket.len())]\n                               ^^^^^^^^^^^^^^^\nAttributeError: module 'WatchSocket' has no attribute 'len'","exception_name":"AttributeError"}
{"level":"ERROR","location":"[On_message:1443] data_ws","message":"'symbol'","timestamp":"2024-05-31 21:33:11,361+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/Users/krfinance18/Desktop/Python/test/lib/python3.12/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1434, in On_message\n    self.OnMessage(message)\n  File \"/Users/krfinance18/Desktop/Python/liveadata.py\", line 16, in onmessage\n    symbbol1 = message['symbol']\n               ~~~~~~~^^^^^^^^^^\nKeyError: 'symbol'","exception_name":"KeyError"}
{"level":"ERROR","location":"[On_message:1443] data_ws","message":"'symbol'","timestamp":"2024-05-31 21:33:12,910+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/Users/krfinance18/Desktop/Python/test/lib/python3.12/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1434, in On_message\n    self.OnMessage(message)\n  File \"/Users/krfinance18/Desktop/Python/liveadata.py\", line 16, in onmessage\n    symbbol1 = message['symbol']\n               ~~~~~~~^^^^^^^^^^\nKeyError: 'symbol'","exception_name":"KeyError"}
{"level":"ERROR","location":"[on_open:1519] data_ws","message":"'module' object is not subscriptable","timestamp":"2024-05-31 21:34:19,246+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/Users/krfinance18/Desktop/Python/test/lib/python3.12/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1517, in on_open\n    self.OnOpen()\n  File \"/Users/krfinance18/Desktop/Python/liveadata.py\", line 55, in onopen\n    symbols = watchSocket[i]\n              ~~~~~~~~~~~^^^\nTypeError: 'module' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[On_message:1443] data_ws","message":"'symbol'","timestamp":"2024-05-31 21:34:20,160+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/Users/krfinance18/Desktop/Python/test/lib/python3.12/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1434, in On_message\n    self.OnMessage(message)\n  File \"/Users/krfinance18/Desktop/Python/liveadata.py\", line 16, in onmessage\n    symbbol1 = message['symbol']\n               ~~~~~~~^^^^^^^^^^\nKeyError: 'symbol'","exception_name":"KeyError"}
{"level":"ERROR","location":"[On_message:1443] data_ws","message":"'symbol'","timestamp":"2024-05-31 21:34:21,759+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/Users/krfinance18/Desktop/Python/test/lib/python3.12/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1434, in On_message\n    self.OnMessage(message)\n  File \"/Users/krfinance18/Desktop/Python/liveadata.py\", line 16, in onmessage\n    symbbol1 = message['symbol']\n               ~~~~~~~^^^^^^^^^^\nKeyError: 'symbol'","exception_name":"KeyError"}
{"level":"ERROR","location":"[On_message:1443] data_ws","message":"'symbol'","timestamp":"2024-05-31 21:35:21,530+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/Users/krfinance18/Desktop/Python/test/lib/python3.12/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1434, in On_message\n    self.OnMessage(message)\n  File \"/Users/krfinance18/Desktop/Python/liveadata.py\", line 16, in onmessage\n    symbbol1 = message['symbol']\n               ~~~~~~~^^^^^^^^^^\nKeyError: 'symbol'","exception_name":"KeyError"}
{"level":"ERROR","location":"[On_message:1443] data_ws","message":"'symbol'","timestamp":"2024-05-31 21:36:02,079+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/Users/krfinance18/Desktop/Python/test/lib/python3.12/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1434, in On_message\n    self.OnMessage(message)\n  File \"/Users/krfinance18/Desktop/Python/liveadata.py\", line 16, in onmessage\n    symbbol1 = message['symbol']\n               ~~~~~~~^^^^^^^^^^\nKeyError: 'symbol'","exception_name":"KeyError"}
{"level":"ERROR","location":"[on_open:1519] data_ws","message":"'module' object is not subscriptable","timestamp":"2024-05-31 21:36:02,092+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/Users/krfinance18/Desktop/Python/test/lib/python3.12/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1517, in on_open\n    self.OnOpen()\n  File \"/Users/krfinance18/Desktop/Python/liveadata.py\", line 55, in onopen\n    symbols = watchSocket[i]\n              ~~~~~~~~~~~^^^\nTypeError: 'module' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[On_message:1443] data_ws","message":"'symbol'","timestamp":"2024-05-31 21:36:29,379+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/Users/krfinance18/Desktop/Python/test/lib/python3.12/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1434, in On_message\n    self.OnMessage(message)\n  File \"/Users/krfinance18/Desktop/Python/liveadata.py\", line 16, in onmessage\n    symbbol1 = message['symbol']\n               ~~~~~~~^^^^^^^^^^\nKeyError: 'symbol'","exception_name":"KeyError"}
{"level":"ERROR","location":"[On_message:1443] data_ws","message":"'symbol'","timestamp":"2024-05-31 21:36:35,430+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/Users/krfinance18/Desktop/Python/test/lib/python3.12/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1434, in On_message\n    self.OnMessage(message)\n  File \"/Users/krfinance18/Desktop/Python/liveadata.py\", line 16, in onmessage\n    symbbol1 = message['symbol']\n               ~~~~~~~^^^^^^^^^^\nKeyError: 'symbol'","exception_name":"KeyError"}
{"level":"ERROR","location":"[on_open:1519] data_ws","message":"'module' object is not subscriptable","timestamp":"2024-05-31 21:36:35,432+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/Users/krfinance18/Desktop/Python/test/lib/python3.12/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1517, in on_open\n    self.OnOpen()\n  File \"/Users/krfinance18/Desktop/Python/liveadata.py\", line 55, in onopen\n    symbols = watchSocket[i]\n              ~~~~~~~~~~~^^^\nTypeError: 'module' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[On_message:1443] data_ws","message":"'symbol'","timestamp":"2024-05-31 21:39:27,438+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/Users/krfinance18/Desktop/Python/test/lib/python3.12/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1434, in On_message\n    self.OnMessage(message)\n  File \"/Users/krfinance18/Desktop/Python/liveadata.py\", line 16, in onmessage\n    symbbol1 = message['symbol']\n               ~~~~~~~^^^^^^^^^^\nKeyError: 'symbol'","exception_name":"KeyError"}
{"level":"ERROR","location":"[On_message:1443] data_ws","message":"'symbol'","timestamp":"2024-05-31 21:39:28,589+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/Users/krfinance18/Desktop/Python/test/lib/python3.12/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1434, in On_message\n    self.OnMessage(message)\n  File \"/Users/krfinance18/Desktop/Python/liveadata.py\", line 16, in onmessage\n    symbbol1 = message['symbol']\n               ~~~~~~~^^^^^^^^^^\nKeyError: 'symbol'","exception_name":"KeyError"}
{"level":"ERROR","location":"[On_message:1443] data_ws","message":"'symbol'","timestamp":"2024-05-31 21:39:29,850+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/Users/krfinance18/Desktop/Python/test/lib/python3.12/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1434, in On_message\n    self.OnMessage(message)\n  File \"/Users/krfinance18/Desktop/Python/liveadata.py\", line 16, in onmessage\n    symbbol1 = message['symbol']\n               ~~~~~~~^^^^^^^^^^\nKeyError: 'symbol'","exception_name":"KeyError"}
{"level":"ERROR","location":"[On_message:1443] data_ws","message":"'symbol'","timestamp":"2024-05-31 21:42:14,970+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/Users/krfinance18/Desktop/Python/test/lib/python3.12/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1434, in On_message\n    self.OnMessage(message)\n  File \"/Users/krfinance18/Desktop/Python/liveadata.py\", line 16, in onmessage\n    symbbol1 = message['symbol']\n               ~~~~~~~^^^^^^^^^^\nKeyError: 'symbol'","exception_name":"KeyError"}
{"level":"ERROR","location":"[On_message:1443] data_ws","message":"'symbol'","timestamp":"2024-05-31 21:42:16,889+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/Users/krfinance18/Desktop/Python/test/lib/python3.12/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1434, in On_message\n    self.OnMessage(message)\n  File \"/Users/krfinance18/Desktop/Python/liveadata.py\", line 16, in onmessage\n    symbbol1 = message['symbol']\n               ~~~~~~~^^^^^^^^^^\nKeyError: 'symbol'","exception_name":"KeyError"}
{"level":"ERROR","location":"[On_message:1443] data_ws","message":"'symbol'","timestamp":"2024-05-31 21:42:20,733+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/Users/krfinance18/Desktop/Python/test/lib/python3.12/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1434, in On_message\n    self.OnMessage(message)\n  File \"/Users/krfinance18/Desktop/Python/liveadata.py\", line 16, in onmessage\n    symbbol1 = message['symbol']\n               ~~~~~~~^^^^^^^^^^\nKeyError: 'symbol'","exception_name":"KeyError"}
{"level":"ERROR","location":"[On_message:1443] data_ws","message":"'symbol'","timestamp":"2024-05-31 21:45:49,766+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/Users/krfinance18/Desktop/Python/test/lib/python3.12/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1434, in On_message\n    self.OnMessage(message)\n  File \"/Users/krfinance18/Desktop/Python/liveadata.py\", line 16, in onmessage\n    symbbol1 = message['symbol']\n               ~~~~~~~^^^^^^^^^^\nKeyError: 'symbol'","exception_name":"KeyError"}
{"level":"ERROR","location":"[On_message:1443] data_ws","message":"'symbol'","timestamp":"2024-05-31 21:45:51,291+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/Users/krfinance18/Desktop/Python/test/lib/python3.12/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1434, in On_message\n    self.OnMessage(message)\n  File \"/Users/krfinance18/Desktop/Python/liveadata.py\", line 16, in onmessage\n    symbbol1 = message['symbol']\n               ~~~~~~~^^^^^^^^^^\nKeyError: 'symbol'","exception_name":"KeyError"}
{"level":"ERROR","location":"[On_message:1443] data_ws","message":"'symbol'","timestamp":"2024-05-31 21:45:52,322+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/Users/krfinance18/Desktop/Python/test/lib/python3.12/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1434, in On_message\n    self.OnMessage(message)\n  File \"/Users/krfinance18/Desktop/Python/liveadata.py\", line 16, in onmessage\n    symbbol1 = message['symbol']\n               ~~~~~~~^^^^^^^^^^\nKeyError: 'symbol'","exception_name":"KeyError"}
{"level":"ERROR","location":"[On_message:1443] data_ws","message":"'symbol'","timestamp":"2024-05-31 21:47:50,292+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/Users/krfinance18/Desktop/Python/test/lib/python3.12/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1434, in On_message\n    self.OnMessage(message)\n  File \"/Users/krfinance18/Desktop/Python/liveadata.py\", line 16, in onmessage\n    symbbol1 = message['symbol']\n               ~~~~~~~^^^^^^^^^^\nKeyError: 'symbol'","exception_name":"KeyError"}
{"level":"ERROR","location":"[On_message:1443] data_ws","message":"'symbol'","timestamp":"2024-05-31 21:47:53,492+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/Users/krfinance18/Desktop/Python/test/lib/python3.12/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1434, in On_message\n    self.OnMessage(message)\n  File \"/Users/krfinance18/Desktop/Python/liveadata.py\", line 16, in onmessage\n    symbbol1 = message['symbol']\n               ~~~~~~~^^^^^^^^^^\nKeyError: 'symbol'","exception_name":"KeyError"}
{"level":"ERROR","location":"[On_message:1443] data_ws","message":"'symbol'","timestamp":"2024-05-31 21:47:54,792+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/Users/krfinance18/Desktop/Python/test/lib/python3.12/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1434, in On_message\n    self.OnMessage(message)\n  File \"/Users/krfinance18/Desktop/Python/liveadata.py\", line 16, in onmessage\n    symbbol1 = message['symbol']\n               ~~~~~~~^^^^^^^^^^\nKeyError: 'symbol'","exception_name":"KeyError"}
